# Generated by Django 4.1 on 2022-09-14 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppConcesionaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes'),
        ),
    ]
