# Generated by Django 4.1 on 2022-09-14 23:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppConcesionaria', '0002_vehiculos_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculos',
            name='fechaDePublicacion',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
