# Generated by Django 4.1 on 2022-09-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppConcesionaria', '0005_alter_vehiculos_fechadepublicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculos',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes'),
        ),
    ]
