# Generated by Django 4.1 on 2022-09-21 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppConcesionaria', '0006_alter_vehiculos_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculos',
            name='fechaDePublicacion',
        ),
    ]
