# Generated by Django 4.1 on 2022-09-21 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppConcesionaria', '0007_remove_vehiculos_fechadepublicacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clientes',
        ),
        migrations.DeleteModel(
            name='Empleados',
        ),
    ]
