# Generated by Django 4.1 on 2022-09-22 23:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppConcesionaria', '0008_delete_clientes_delete_empleados'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculos',
            name='fechaDePublicacion',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
